### ISSUE TITLE
Determine ALL Zip Codes for Major Cities

### ISSUE THREAD

**Issue by bendres97** [CSIS-BU/cis445-project1-poison-jab#14]
* Chicago
* New York
* St. Louis
* Houston
* Los Angeles
* Seattle
* Miami
* D.C.
* Denver
* Atlanta
* Madison
* Miami
* Anchorage
* Honolulu
* San Juan, Puerto Rico

Place into JSON format so that we have City : Zip pairs that can be referenced by our code.

**Comment by jbren4** [comment]
To clarify do you want a zip code for each city or every single zip codes for each major city?

**Comment by BryanEndres** [comment]
Remove these from the driver. They should be in a JSON document and each city should have multiple zip codes.
